---
# tasks file for nginx_test
- name: check nginx home existin
  stat:
    path: /usr/sbin/nginx
  register: p

- name: nginx version check
  when: p.stat.exists == true
  command: nginx -v
  register: mynginx
  ignore_errors: yes

- debug:
    msg:
    - '{{ p.stat.path }}'
    - '{{ mynginx.stderr }}'
  when: p.stat.exists == true
