---
# tasks file for nginx
- name: install nginx
  apt:
    name: nginx
    state: latest
  become: yes
  become_method: sudo

- name: provisining tomcat through nginx
  shell: |
      echo '
      server {
      listen 80;
      server_name localhost;

      location / {
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Server $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_pass http://127.0.0.1:8080/;
        }
      }' > /etc/nginx/conf.d/tomcat_proxy.conf
  args:
    executable: /bin/bash
  become: yes
  become_method: sudo

- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: yes
  become_method: sudo

- name: restart tomcat
  service:
    name: tomcat
    state: restarted
  become: yes
  become_method: sudo

- name: wait for tomcat to start
  wait_for: port='{{http_port}}'
