---
# tasks file for tomcat_test
- name: check tomcat home existin
  stat:
    path: "{{ tomcat_home }}{{ tomcat_version }}"
  register: p

- debug:
    msg:
    - 'Tomcat not installed'
  when: p.stat.exists == false

- name: tomcat version check
  when: p.stat.exists == true
  command: " sh {{ tomcat_home }}{{ tomcat_version }}/bin/version.sh"
  register: mytomcat
#  ignore_errors: yes

- debug:
    msg:
    - '{{ p.stat.path }}'
    - '{{ mytomcat.stdout_lines }}'
  when: p.stat.exists == true
