apiVersion: apps/v1beta2 # for versions before 1.7.0 use apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: myhtml
        env:
        - name: MYPOD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
#        command: ["printenv"]
#        args: ["MYPOD_NAME"]
#        command: ["/bin/sh"]
#        args: ["-c", "/usr/share/nginx/html/env.sh > /usr/share/nginx/html/index.html && sleep 10 && exit 0"]
      volumes:
      - name: myhtml
        persistentVolumeClaim:
         claimName: pvc-nginx
#      nodeSelector:
#        labels: beta.kubernetes.io/master
#        envFrom:
#        - configMapRef:
#            name: special-config
        