apiVersion: v1
kind: Service
metadata: 
    name: nginx-svc
    labels:
        app: nginxv1
spec:
    type: NodePort
    ports:
    -   port: 80
        nodePort: 300003
        protocol: TCP
    selector:
        app: nginxv1